# Site settings
title: guifibages
email: info@guifibages.cat
description: "L'associació Guifibages promou la xarxa lliure Guifi.net al Bages."
baseurl: ""
url: "http://guifibages.cat"

# Build settings
markdown: kramdown
permalink: pretty